config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"


  resources :users, only: [:show] do
    resources :protests, only: [:index] do
      resources :transportations do
        resources :passengers
      end
    end
  end


  resources :protests do
    resources :attendances, only: [:create, :destroy]
  end


end

app/models/transportation.rb
class Transportation < ApplicationRecord
  belongs_to :destination, class_name: :Protest
  belongs_to :transporter, class_name: :User

  has_many :passengers
  has_many :users, through: :passengers
end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  def index
    @protest = Protest.find(params[:protest_id])
    @transportations = Transportation.where(destination_id: @protest.id)
    @transportations.each do |transportation|
      passengers = Passenger.where(transportation_id: transportation.id)
      passengers.each do |p|
        if p.user_id == current_user.id
          @already_picked_transportation = transportation
          @passenger = p
        end
      end
    end
  end

  def new
    @protest = Protest.find(params[:protest_id])
    @transportation = Transportation.new
  end

  def create
    @protest = Protest.find(params[:protest_id])
    @transportation = Transportation.new(transportation_params)
    @transportation.destination_id = @protest.id
    @transportation.transporter_id = current_user.id

    respond_to do |format|
      if @transportation.save
        format.html { redirect_to user_protest_transportation_path(id: @transportation.id), notice: 'Transportation was successfully created.' }
        format.json { render :show, status: :created, location: @transportation }
      else
        format.html { render :new }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end

  end

  def show
    @transportation = Transportation.find(params[:id])
    @protest = Protest.find(@transportation.destination_id)
  end

  def edit
  end

  def update
  end

  def destroy
  end



  private

  def transportation_params
    params.require(:transportation).permit(:pickup_location, :vehicle, :capacity, :destination)
  end
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/views/transportations/create.html.erb
<h1>You provided transportation for <%= @protest.name %></h1>

<h2>Transportation details: </h2>
<p>
  <ul>
    <li>Vehicle: <%= @transportation.vehicle %></li>
    <li>Capacity: <%= @transportation.capacity %></li>
    <li>Pick Up Location: <%= @transportation.pickup_location %></li>
  </ul>
</p>


<%= link_to "OK", protests_path %>

app/views/transportations/destroy.html.erb
<h1>Transportations#destroy</h1>
<p>Find me in app/views/transportations/destroy.html.erb</p>

app/views/transportations/edit.html.erb
<h1>Transportations#edit</h1>
<p>Find me in app/views/transportations/edit.html.erb</p>

app/views/transportations/index.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<h1 class="text-center">Transportations for <%= @protest.name %></h1>

<div class="container">
  <div class="panel-body ">
						<input type="text" class="form-control" id="dev-table-filter" data-action="filter" data-filters="#dev-table" placeholder="Filter Developers" />
					</div>
					<table class="table table-hover" id="dev-table">
						<thead>
							<tr>
								<th>Leaving From</th>
								<th>Date and Time</th>
								<th>Action</th>
                <th>Edit</th>
							</tr>
						</thead>

						<tbody>
                <% @transportations.each do |transportation| %>
                <tr>
                  <td><%= transportation.pickup_location %></td>
                  <td><%= @protest.starts_at.to_formatted_s(:short).to_date %></td>
                  <% if @already_picked_transportation == transportation %>
                      <td><%= button_to "Joined",
                      user_protest_transportation_passengers_path(transportation_id: transportation.id),
                      class: "btn btn-primary"  %></td>
                      <td><%= link_to "Cancel the Ride",
                      user_protest_transportation_passenger_path(id: @passenger.id, transportation_id: transportation.id),
                      class: "btn btn-primary"  %></td>
                  <% else %>
                    <td><%= button_to "Join",
                    user_protest_transportation_passengers_path(transportation_id: transportation.id),
                    class: "btn btn-primary"  %></td>
                  <% end %>

                </tr>
                <% end %>
						</tbody>
					</table>
				</div>
			</div>
</div>

app/views/transportations/new.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header"><h2>Provide a Transportation for <%= @protest.name %></h2></div>
    <div class="card-block">

    <%= form_for(@transportation, url:  user_protest_transportations_path, html: {multipart: true}) do |f| %>
      <div class="form-group">
        <%= f.label :vehicle %>
        <%= f.text_field :vehicle, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :capacity %>
        <%= f.text_field :capacity, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :pickup_location %>
        <%= f.text_field :pickup_location, class: "form-control" %>
      </div>


      <div class="form-group">
        <%= f.submit "Add Transportation", class: "btn btn-primary" %>
        <%= link_to "Skip", protests_path, class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>


  </div>
  </div>

app/views/transportations/show.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>

  <style>
      tab1 { padding-left: 1em; }
  </style>
  
<h2 class="text-center"><tab1>Transportation details: </h2>

  <ul class="list-group">
    <li class="list-group-item"><strong>Event:<tab1></strong><%= @protest.name %></li>
    <li class="list-group-item"><strong>Vehicle:<tab1></strong><%= @transportation.vehicle %></li>
    <li class="list-group-item"><strong>Capacity:<tab1></strong><%= @transportation.capacity %></li>
    <li class="list-group-item"><strong>Pick Up Location:<tab1></strong><%= @transportation.pickup_location %></li>
  </ul>

  <%= link_to "OK", protests_path, class: "btn btn-primary ml-3 mt-3" %>

app/views/transportations/update.html.erb
<h1>Transportations#update</h1>
<p>Find me in app/views/transportations/update.html.erb</p>