config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"


  resources :users, only: [:show] do
    resources :protests, only: [:index] do
      resources :transportations do
        resources :passengers
      end
    end
  end


  resources :protests do
    resources :attendances, only: [:create, :destroy]
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, :last_name, :email,  presence: true

  has_many :protests, foreign_key: :creator_id

  has_many :attendances
  has_many :attended_protests, through: :attendances, source: :protest

  has_many :passengers
  has_many :transportations, through: :passengers

  def attending?(protest)
    if Attendance.exists?(user_id: self.id, protest_id: protest.id)
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :user_is_current_user

  def show
    @user = current_user
  end

  private

  def user_is_current_user
    unless current_user.id == params[:id].to_i
      redirect_to root_path
    end
  end
end

app/views/users/show.html.erb
<div class="col-md-12">
  <div class="card">
    <h3 class="card-header">Hi <%= @user.first_name %>!</h3>
    <div class="card-block">
      <div class="row">
        <div class="col-sm-6">
          <div class="card">
            <div class="card-block">
              <h3 class="card-title">My Events</h3>
                <ul class="list-group">
                  <%  @user.protests.each do |protest| %>
                    <li class="list-group-item"><%= protest.name %></li>
                  <% end %>
                </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="card">
            <div class="card-block">
              <h3 class="card-title">Events Attending</h3>
                <ul class="list-group">
                  <% @user.attended_protests.each do |protest_attending| %>
                    <li class="list-group-item"><%= protest_attending.name %> </li>
                  <% end %>
                </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-footer">
      <%= link_to "Create Event", new_protest_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>