config/routes.rb
Rails.application.routes.draw do



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"


  resources :users, only: [:show] do
    resources :protests, only: [:index] do
      resources :transportations do
        resources :passengers
      end
    end
  end


  resources :protests do
    resources :attendances, only: [:create, :destroy]
  end


end

app/models/protest.rb
class Protest < ApplicationRecord
  validates :name, :description, :location,
            :starts_at, :creator, presence: true

  has_attached_file :image, styles: {thumb: "100x100#",
                                     medium: "400x600#" },
                                     default_url: ":style/missing.png"
                                     
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :creator, class_name: :User

  has_many :attendances
  has_many :users, through: :attendances

  has_many :transportations
end

app/controllers/protests_controller.rb
class ProtestsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @protests = Protest.all
  end

  def show
    @protest = Protest.find(params[:id])
    @user = current_user
  end

  def new
    @protest = Protest.new
  end

  def edit
    @protest = Protest.find(params[:id])
  end

  def create
    @protest = Protest.new(protest_params)
    @protest.creator = current_user
    respond_to do |format|
      if @protest.save
        format.html { redirect_to @protest, notice: 'Protest was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    @protest = Protest.find(params[:id])

    respond_to do |format|
      if @protest.update(protest_params)
        format.html { redirect_to @protest, notice: 'Protest was successfully updated.' }
      else
        format.html {render :edit }
      end
    end
  end

  def destroy
    @protest = Protest.find(params[:id])
    @protest.destroy

    redirect_to protests_path
  end

  private

  def protest_params
    params.require(:protest).permit(:name, :description, :location, :starts_at, :creator, :image)
  end

end

app/views/protests/edit.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header"><h2>Create A Protest</h2></div>
    <div class="card-block">

    <%= form_for(@protest, method: :put, html: {multipart: true}) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :starts_at %>
        <%= f.date_field :starts_at, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: "form-control"%>
     </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, as: :file, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Edit", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>


  </div>
  </div>

app/views/protests/index.html.erb
<h1>Protests</h1>
<div class="container">
  <div class="row">
    <div class="[ col-xs-12 col-sm-offset-2 col-sm-8 ]">
      <ul class="event-list">
        <% @protests.each do |protest| %>
          <li>
            <time datetime="2014-07-20">
              <span class="day"><%= to_day(protest.starts_at)%></span>
              <span class="month"><%= to_month(protest.starts_at) %></span>
              <span class="year"><%= to_year(protest.starts_at) %></span>
              <span class="time"><%= to_year(protest.starts_at) %></span>
            </time>
            <a href="/protests/<%=protest.id%>"><%= image_tag protest.image.url(:thumb) %></a>
            <div class="info">
              <h2 class="title"><%= protest.name %></h2>
              <p class="desc"><%= protest.location %></p>
            </div>
            <div class="social">
              <ul>
                <li class="facebook" style="width:33%;"><a href="#facebook"><span class="fa fa-facebook"></span></a></li>
                <li class="twitter" style="width:34%;"><a href="#twitter"><span class="fa fa-twitter"></span></a></li>
                <li class="google-plus" style="width:33%;"><a href="#google-plus"><span class="fa fa-google-plus"></span></a></li>
              </ul>
            </div>
          </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/protests/new.html.erb
<div class="col-md-12">
  <div class="card">
    <div class="card-header"><h2>Create A Protest</h2></div>
    <div class="card-block">

    <%= form_for(@protest, url: protests_path, html: {multipart: true}) do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :location %>
        <%= f.text_field :location, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label "Date:" %>
        <%= f.date_field :starts_at, class: "form-control"%>
      </div>

     <div class="form-group">
       <%= f.label "Time:" %>
       <%= f.time_field :starts_at, class: "form-control"%>
     </div>

      <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image, as: :file, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit "Create", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>


  </div>
</div>

app/views/protests/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12", align="center">
      <div class="card">
        <div class="card-header">
          <h1><%= @protest.name %></h1>
        </div>
        <div class="card-block">
          <div class="card-img-top"><%= image_tag @protest.image.url(:medium), class: "img-thumbnail" %></div>
            <% if current_user == @protest.creator %>
              <%= link_to 'Edit', edit_protest_path %>
              <%= link_to 'Delete', protest_path(@protest), method: :delete, data: { confirm: "We need you !"} %>
            <% end %>
            <a class="nav-link" href="/users/<%= @protest.creator_id %>/protests/<%= @protest.id %>/transportations/new">Add Transportation</a>

            <ul class="list-group list-group-flush align-items-center">
              <h4 class="card-title">Description:</h4>
              <p class="card-text"><%= @protest.description %></p>
              <h4 class="card-title">Location:</h4>
              <li class="list-group-item"><%= @protest.location %></li>
              <h4 class="card-title">Date:</h4>
              <li class="list-group-item"><%= to_date(@protest.starts_at) %></li>
              <h4 class="card-title">Time:</h4>
              <li class="list-group-item"><%= to_time(@protest.starts_at) %></li>
            </ul>

        </div>

        <div class="card-footer">

            <%= button_to "Attend", protest_attendances_path(@protest), class: "btn btn-primary", id: "attend" %>

          <div class="container", id="questions">
            <%= button_to "Unattend", protest_attendance_path(@protest), method: :delete, data: {confirm: "Are you sure you dont want to be part of the revolution?"}, class: "btn btn-primary", id: "unattend" %>

          <div class="row">
            <div class="col-sm-6">
              <div class="card">
                <div class="card-block">
                  <h3 class="card-title">Provide Transportation</h3>
                  <p class="card-text">Help us in our effort to mobilize people, if you have space in your car share it with someone near you.</p>
                  <%= link_to 'Provide Transportation', new_user_protest_transportation_path(@user, @protest), class: "btn btn-primary" %>
                </div>
              </div>
            </div>
              <div class="col-sm-6">
                <div class="card">
                  <div class="card-block">
                    <h3 class="card-title">Need A Ride?</h3>
                    <p class="card-text">Find people near you willing to share a seat who are coming to the event. We are all in this together!.</p>
                    <%= link_to 'Get A Ride',  user_protest_transportations_path(@user, @protest, @transportation), class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>